### PR TITLE
Add numeral to format values in scale and legend

### LINKED ISSUE #1: [REQUEST] Show lowest and largest number
Would be pretty useful, if the inputs are below 0, it'd show the lowest and largest number on the scale and in legend. :100: 

Right now, it only shows 0.00, but I'm working with numebrs like 0.0000001. :cactus:

### PR DESCRIPTION
**Pull request by gribnoysup**
Closes #1

### CODE REVIEW

**Comment by Mobilpadde** [comment]
Awesome! :+1:

**Comment by gribnoysup** [comment]
@Mobilpadde found a small bug, can you try again just to make sure? 😅 Published again as a  `@next` tag

**Comment by Mobilpadde** [comment]
Will do! Gimme a sec.

**Comment by Mobilpadde** [comment]
Great! It's working! :smiley_cat: :+1: :100:

**Pull request merged**
